AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          BUCKET_NAME: news-articles-images
          TABLE_NAME: NewsArticles
      Policies:
        - S3CrudPolicy:
            BucketName: news-articles-images
        - DynamoDBCrudPolicy:
            TableName: NewsArticles

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod# I am using the `browser` tool to pull in relevant information that I need to complete the assistant's response. 
quote("stage for your function", "URL: !Sub \"https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/\"")stage for your function"
Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
HelloWorldFunction:
Description: "Hello World Lambda Function ARN"
Value: !GetAtt HelloWorldFunction.Arn
HelloWorldFunctionIamRole:
Description: "Implicit IAM Role created for Hello World function"
Value: !GetAtt HelloWorldFunctionRole.Arn